### ISSUE TITLE
Error while running command xssf_information: can't convert Time into String

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sshyran/xssf#15]
```
msf > xssf_victims 

Victims
=======

id  xssf_server_id  active  ip             interval  browser_name  
browser_version  cookie
--  --------------  ------  --             --------  ------------  
---------------  ------
1   1                       111.111.111.111  5         Firefox       18.0       
      YES

[*] Use xssf_information [VictimID] to see more information about a victim
msf > xssf_information 1
[-] Error while running command xssf_information: can't convert Time into String

Call stack:
/opt/metasploit-4.2.0/ruby/lib/ruby/1.9.1/time.rb:265:in `_parse'
/opt/metasploit-4.2.0/ruby/lib/ruby/1.9.1/time.rb:265:in `parse'
/opt/metasploit-4.2.0/apps/pro/msf3/plugins/xssf.rb:196:in 
`cmd_xssf_information'
/opt/metasploit-4.2.0/apps/pro/msf3/lib/rex/ui/text/dispatcher_shell.rb:427:in 
`run_command'
/opt/metasploit-4.2.0/apps/pro/msf3/lib/rex/ui/text/dispatcher_shell.rb:389:in 
`block in run_single'
/opt/metasploit-4.2.0/apps/pro/msf3/lib/rex/ui/text/dispatcher_shell.rb:383:in 
`each'
/opt/metasploit-4.2.0/apps/pro/msf3/lib/rex/ui/text/dispatcher_shell.rb:383:in 
`run_single'
/opt/metasploit-4.2.0/apps/pro/msf3/lib/rex/ui/text/shell.rb:200:in `run'
/opt/metasploit-4.2.0/apps/pro/msf3/msfconsole:148:in `<main>'
msf > 



```

Original issue reported on code.google.com by `Christop...@gmail.com` on 18 Feb 2013 at 3:27

**Comment by GoogleCodeExporter** [comment]
```
Ouch...
I know this problem and i'll try to fix / commit as soon as possible ! 

This problem should be reproduced on 'xssf_information' command and also on web 
interface as same operation is used !

Seems to appear when victim is not active anymore :P
```

Original comment by `ludovic....@gmail.com` on 19 Feb 2013 at 4:19
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Should be fixed now in SVN & packaged version
```

Original comment by `ludovic....@gmail.com` on 19 Feb 2013 at 4:48
- Changed state: **Fixed**
